# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [9]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [10]:
### [your code here]
print(np.__version__)

print(np.show_config())

1.26.4
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: /opt/anaconda3/include
    lib directory: /opt/anaconda3/lib
    name: openblas
    openblas configuration: USE_64BITINT= DYNAMIC_ARCH=1 DYNAMIC_OLDER= NO_CBLAS=
      NO_LAPACK=0 NO_LAPACKE= NO_AFFINITY=1 USE_OPENMP=0 CORE2 MAX_THREADS=128
    pc file directory: /opt/anaconda3/lib/pkgconfig
    version: 0.3.21
  lapack:
    detection method: internal
    found: true
    include directory: unknown
    lib directory: unknown
    name: dep4429404432
    openblas configuration: unknown
    pc file directory: unknown
    version: 1.26.4
Compilers:
  c:
    args: -march=core2, -mtune=haswell, -mssse3, -ftree-vectorize, -fPIC, -fPIE, -fstack-protector-strong,
      -O2, -pipe, -isystem, /opt/anaconda3/include, -fdebug-prefix-map=/var/folders/c_/qfmhj66j0tn016nkx_th4hxm0000gp/T/abs_b7iptlxgej/croot/numpy_and_numpy_base_1708638622773/work=/usr/local/src/conda/numpy-base-1.26.4,
      -fdeb

### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [11]:
### [your code here]
a = np.random.randn(2, 3, 5)




### 4. Print a.


In [12]:
### [your code here]
print(a)

[[[ 0.17499364 -0.3359316  -1.15177781  0.58397169  1.68739868]
  [ 0.32145243  0.57639285  0.69950391  0.85946442 -0.15014967]
  [-1.12995357  2.37950164  0.35568731  0.07897753  0.08327513]]

 [[ 0.6161813  -0.43272041  0.84547311  0.60593327 -0.0049957 ]
  [-0.55322452 -0.88221157 -0.07118612 -0.23664213 -0.1875449 ]
  [-1.04330466  0.50807495 -1.86519076 -0.50559052  0.0696973 ]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [13]:
### [your code here]
b = np.ones((5, 2, 3))



### 6. Print b.


In [14]:
### [your code here]
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [15]:
a.shape == b.shape


False


### 8. Are you able to add a and b? Why or why not?


In [16]:
### [your code here]
# it is not possible because both arrays do not have the same shape



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [17]:
### [your code here]
c = b.transpose(1, 2, 0)
print(c)


[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [18]:
### [your code here]
d = a + c
print(d)
# now both arrays have the same shape and can be added

[[[ 1.17499364  0.6640684  -0.15177781  1.58397169  2.68739868]
  [ 1.32145243  1.57639285  1.69950391  1.85946442  0.84985033]
  [-0.12995357  3.37950164  1.35568731  1.07897753  1.08327513]]

 [[ 1.6161813   0.56727959  1.84547311  1.60593327  0.9950043 ]
  [ 0.44677548  0.11778843  0.92881388  0.76335787  0.8124551 ]
  [-0.04330466  1.50807495 -0.86519076  0.49440948  1.0696973 ]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [19]:
### [your code here]
print(a)
print("")
print(d)

print(d-a) #shows that the difference is 1 or c



[[[ 0.17499364 -0.3359316  -1.15177781  0.58397169  1.68739868]
  [ 0.32145243  0.57639285  0.69950391  0.85946442 -0.15014967]
  [-1.12995357  2.37950164  0.35568731  0.07897753  0.08327513]]

 [[ 0.6161813  -0.43272041  0.84547311  0.60593327 -0.0049957 ]
  [-0.55322452 -0.88221157 -0.07118612 -0.23664213 -0.1875449 ]
  [-1.04330466  0.50807495 -1.86519076 -0.50559052  0.0696973 ]]]

[[[ 1.17499364  0.6640684  -0.15177781  1.58397169  2.68739868]
  [ 1.32145243  1.57639285  1.69950391  1.85946442  0.84985033]
  [-0.12995357  3.37950164  1.35568731  1.07897753  1.08327513]]

 [[ 1.6161813   0.56727959  1.84547311  1.60593327  0.9950043 ]
  [ 0.44677548  0.11778843  0.92881388  0.76335787  0.8124551 ]
  [-0.04330466  1.50807495 -0.86519076  0.49440948  1.0696973 ]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 12. Multiply a and c. Assign the result to e.


In [20]:
### [your code here]
e = a * c
print(e)


[[[ 0.17499364 -0.3359316  -1.15177781  0.58397169  1.68739868]
  [ 0.32145243  0.57639285  0.69950391  0.85946442 -0.15014967]
  [-1.12995357  2.37950164  0.35568731  0.07897753  0.08327513]]

 [[ 0.6161813  -0.43272041  0.84547311  0.60593327 -0.0049957 ]
  [-0.55322452 -0.88221157 -0.07118612 -0.23664213 -0.1875449 ]
  [-1.04330466  0.50807495 -1.86519076 -0.50559052  0.0696973 ]]]




### 13. Does e equal to a? Why or why not?


In [21]:
### [your code here]
e == a

# yes it is equal, because the multiplicator was 1

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [22]:
### [your code here]
d_max = d.max()
print(d_max)
d_min = d.min()
print(d_min)
d_mean = d.mean()
print(d_mean)



3.3795016436447365
-0.8651907582248166
1.0631851741413392



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [23]:
### [your code here]
f = np.empty((2, 3, 5))
#f = np.empty(d.shape)
print(f)


[[[0.17499364 0.3359316  1.15177781 0.58397169 1.68739868]
  [0.32145243 0.57639285 0.69950391 0.85946442 0.15014967]
  [1.12995357 2.37950164 0.35568731 0.07897753 0.08327513]]

 [[0.6161813  0.43272041 0.84547311 0.60593327 0.0049957 ]
  [0.55322452 0.88221157 0.07118612 0.23664213 0.1875449 ]
  [1.04330466 0.50807495 1.86519076 0.50559052 0.0696973 ]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [26]:
print(d)

[[[ 1.17499364  0.6640684  -0.15177781  1.58397169  2.68739868]
  [ 1.32145243  1.57639285  1.69950391  1.85946442  0.84985033]
  [-0.12995357  3.37950164  1.35568731  1.07897753  1.08327513]]

 [[ 1.6161813   0.56727959  1.84547311  1.60593327  0.9950043 ]
  [ 0.44677548  0.11778843  0.92881388  0.76335787  0.8124551 ]
  [-0.04330466  1.50807495 -0.86519076  0.49440948  1.0696973 ]]]


In [33]:
### [your code here]
for value in range(len(d.flat)):
    if d_min < d.flat[value] < d_mean:
        f.flat[value] = 25
    elif d_mean < d.flat[value] < d_max:
        f.flat[value] = 75
    elif d.flat[value] == d_mean:
        f.flat[value] = 50   
    elif d.flat[value] == d_min:
        f.flat[value] = 0
    elif d.flat[value] == d_max:
        f.flat[value] = 100
print(f)

[[[ 75.  25.  25.  75.  75.]
  [ 75.  75.  75.  75.  25.]
  [ 25. 100.  75.  75.  75.]]

 [[ 75.  25.  75.  75.  25.]
  [ 25.  25.  25.  25.  25.]
  [ 25.  75.   0.  25.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [39]:
### [your code here]
print(d)
print(f)



[[[ 1.17499364  0.6640684  -0.15177781  1.58397169  2.68739868]
  [ 1.32145243  1.57639285  1.69950391  1.85946442  0.84985033]
  [-0.12995357  3.37950164  1.35568731  1.07897753  1.08327513]]

 [[ 1.6161813   0.56727959  1.84547311  1.60593327  0.9950043 ]
  [ 0.44677548  0.11778843  0.92881388  0.76335787  0.8124551 ]
  [-0.04330466  1.50807495 -0.86519076  0.49440948  1.0696973 ]]]
[[[ 75.  25.  25.  75.  75.]
  [ 75.  75.  75.  75.  25.]
  [ 25. 100.  75.  75.  75.]]

 [[ 75.  25.  75.  75.  25.]
  [ 25.  25.  25.  25.  25.]
  [ 25.  75.   0.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [ ]:
### [your code here]